title: CV | Maxim Ovchinnikov
description:  CV
url: https://mvovchinnikov.github.io/cv
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
